/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.11 and the Filter Design Toolbox 4.7.1.
 *
 * Generated on: 30-Jul-2013 18:21:28
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 129
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2010b.app/extern/include/tmwtypes.h 
 */
const int BL = 129;
const short B[129] = {
       16,    -20,     -4,      6,    -20,     11,      2,    -22,     26,
      -12,    -16,     36,    -33,      3,     35,    -53,     34,     15,
      -61,     69,    -25,    -45,     93,    -77,      0,     89,   -124,
       70,     45,   -143,    148,    -41,   -111,    202,   -153,    -18,
      200,   -257,    128,    116,   -307,    294,    -58,   -257,    425,
     -296,    -77,    451,   -544,    237,    306,   -716,    654,    -70,
     -701,   1109,   -742,   -339,   1521,  -1903,    799,   1808,  -5141,
     7927,  23757,   7927,  -5141,   1808,    799,  -1903,   1521,   -339,
     -742,   1109,   -701,    -70,    654,   -716,    306,    237,   -544,
      451,    -77,   -296,    425,   -257,    -58,    294,   -307,    116,
      128,   -257,    200,    -18,   -153,    202,   -111,    -41,    148,
     -143,     45,     70,   -124,     89,      0,    -77,     93,    -45,
      -25,     69,    -61,     15,     34,    -53,     35,      3,    -33,
       36,    -16,    -12,     26,    -22,      2,     11,    -20,      6,
       -4,    -20,     16
};
